/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AppRouteImport } from "./routes/_app"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AppAccessRouteImport } from "./routes/_app/access"
import { Route as AppChangelogRouteImport } from "./routes/_app/changelog"
import { Route as AppCoverageRouteImport } from "./routes/_app/coverage"
import { Route as AppExportsRouteImport } from "./routes/_app/exports"
import { Route as AppIssuesRouteImport } from "./routes/_app/issues"
import { Route as AppSettingsRouteImport } from "./routes/_app/settings"
import { Route as AppVersionsRouteImport } from "./routes/_app/versions"
import { Route as LoginIndexRouteImport } from "./routes/login/index"
import { Route as AppAccessIndexRouteImport } from "./routes/_app/access/index"
import { Route as AppAccessGroupsRouteImport } from "./routes/_app/access/groups"
import { Route as AppAccessTokensRouteImport } from "./routes/_app/access/tokens"
import { Route as AppTranslationsIndexRouteImport } from "./routes/_app/translations/index"
import { Route as AppTranslationsNewRouteImport } from "./routes/_app/translations/new"
import { Route as AppTranslationsLocaleKeyRouteImport } from "./routes/_app/translations/$locale/$key"

const AppRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRoute,
} as any)
const AppAccessRoute = AppAccessRouteImport.update({
  id: "/access",
  path: "/access",
  getParentRoute: () => AppRoute,
} as any)
const AppChangelogRoute = AppChangelogRouteImport.update({
  id: "/changelog",
  path: "/changelog",
  getParentRoute: () => AppRoute,
} as any)
const AppCoverageRoute = AppCoverageRouteImport.update({
  id: "/coverage",
  path: "/coverage",
  getParentRoute: () => AppRoute,
} as any)
const AppExportsRoute = AppExportsRouteImport.update({
  id: "/exports",
  path: "/exports",
  getParentRoute: () => AppRoute,
} as any)
const AppIssuesRoute = AppIssuesRouteImport.update({
  id: "/issues",
  path: "/issues",
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => AppRoute,
} as any)
const AppVersionsRoute = AppVersionsRouteImport.update({
  id: "/versions",
  path: "/versions",
  getParentRoute: () => AppRoute,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccessIndexRoute = AppAccessIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppAccessRoute,
} as any)
const AppAccessGroupsRoute = AppAccessGroupsRouteImport.update({
  id: "/groups",
  path: "/groups",
  getParentRoute: () => AppAccessRoute,
} as any)
const AppAccessTokensRoute = AppAccessTokensRouteImport.update({
  id: "/tokens",
  path: "/tokens",
  getParentRoute: () => AppAccessRoute,
} as any)
const AppTranslationsIndexRoute = AppTranslationsIndexRouteImport.update({
  id: "/translations/",
  path: "/translations/",
  getParentRoute: () => AppRoute,
} as any)
const AppTranslationsNewRoute = AppTranslationsNewRouteImport.update({
  id: "/translations/new",
  path: "/translations/new",
  getParentRoute: () => AppRoute,
} as any)
const AppTranslationsLocaleKeyRoute =
  AppTranslationsLocaleKeyRouteImport.update({
    id: "/translations/$locale/$key",
    path: "/translations/$locale/$key",
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/access": typeof AppAccessRouteWithChildren
  "/changelog": typeof AppChangelogRoute
  "/coverage": typeof AppCoverageRoute
  "/exports": typeof AppExportsRoute
  "/issues": typeof AppIssuesRoute
  "/settings": typeof AppSettingsRoute
  "/versions": typeof AppVersionsRoute
  "/login/": typeof LoginIndexRoute
  "/access/groups": typeof AppAccessGroupsRoute
  "/access/tokens": typeof AppAccessTokensRoute
  "/translations/new": typeof AppTranslationsNewRoute
  "/access/": typeof AppAccessIndexRoute
  "/translations/": typeof AppTranslationsIndexRoute
  "/translations/$locale/$key": typeof AppTranslationsLocaleKeyRoute
}
export interface FileRoutesByTo {
  "/changelog": typeof AppChangelogRoute
  "/coverage": typeof AppCoverageRoute
  "/exports": typeof AppExportsRoute
  "/issues": typeof AppIssuesRoute
  "/settings": typeof AppSettingsRoute
  "/versions": typeof AppVersionsRoute
  "/": typeof AppIndexRoute
  "/login": typeof LoginIndexRoute
  "/access/groups": typeof AppAccessGroupsRoute
  "/access/tokens": typeof AppAccessTokensRoute
  "/translations/new": typeof AppTranslationsNewRoute
  "/access": typeof AppAccessIndexRoute
  "/translations": typeof AppTranslationsIndexRoute
  "/translations/$locale/$key": typeof AppTranslationsLocaleKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app": typeof AppRouteWithChildren
  "/_app/access": typeof AppAccessRouteWithChildren
  "/_app/changelog": typeof AppChangelogRoute
  "/_app/coverage": typeof AppCoverageRoute
  "/_app/exports": typeof AppExportsRoute
  "/_app/issues": typeof AppIssuesRoute
  "/_app/settings": typeof AppSettingsRoute
  "/_app/versions": typeof AppVersionsRoute
  "/_app/": typeof AppIndexRoute
  "/login/": typeof LoginIndexRoute
  "/_app/access/groups": typeof AppAccessGroupsRoute
  "/_app/access/tokens": typeof AppAccessTokensRoute
  "/_app/translations/new": typeof AppTranslationsNewRoute
  "/_app/access/": typeof AppAccessIndexRoute
  "/_app/translations/": typeof AppTranslationsIndexRoute
  "/_app/translations/$locale/$key": typeof AppTranslationsLocaleKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/access"
    | "/changelog"
    | "/coverage"
    | "/exports"
    | "/issues"
    | "/settings"
    | "/versions"
    | "/login/"
    | "/access/groups"
    | "/access/tokens"
    | "/translations/new"
    | "/access/"
    | "/translations/"
    | "/translations/$locale/$key"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/changelog"
    | "/coverage"
    | "/exports"
    | "/issues"
    | "/settings"
    | "/versions"
    | "/"
    | "/login"
    | "/access/groups"
    | "/access/tokens"
    | "/translations/new"
    | "/access"
    | "/translations"
    | "/translations/$locale/$key"
  id:
    | "__root__"
    | "/_app"
    | "/_app/access"
    | "/_app/changelog"
    | "/_app/coverage"
    | "/_app/exports"
    | "/_app/issues"
    | "/_app/settings"
    | "/_app/versions"
    | "/_app/"
    | "/login/"
    | "/_app/access/groups"
    | "/_app/access/tokens"
    | "/_app/translations/new"
    | "/_app/access/"
    | "/_app/translations/"
    | "/_app/translations/$locale/$key"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app"
      path: ""
      fullPath: "/"
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/access": {
      id: "/_app/access"
      path: "/access"
      fullPath: "/access"
      preLoaderRoute: typeof AppAccessRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/changelog": {
      id: "/_app/changelog"
      path: "/changelog"
      fullPath: "/changelog"
      preLoaderRoute: typeof AppChangelogRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/coverage": {
      id: "/_app/coverage"
      path: "/coverage"
      fullPath: "/coverage"
      preLoaderRoute: typeof AppCoverageRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/exports": {
      id: "/_app/exports"
      path: "/exports"
      fullPath: "/exports"
      preLoaderRoute: typeof AppExportsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/issues": {
      id: "/_app/issues"
      path: "/issues"
      fullPath: "/issues"
      preLoaderRoute: typeof AppIssuesRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/settings": {
      id: "/_app/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/versions": {
      id: "/_app/versions"
      path: "/versions"
      fullPath: "/versions"
      preLoaderRoute: typeof AppVersionsRouteImport
      parentRoute: typeof AppRoute
    }
    "/login/": {
      id: "/login/"
      path: "/login"
      fullPath: "/login/"
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/access/": {
      id: "/_app/access/"
      path: "/"
      fullPath: "/access/"
      preLoaderRoute: typeof AppAccessIndexRouteImport
      parentRoute: typeof AppAccessRoute
    }
    "/_app/access/groups": {
      id: "/_app/access/groups"
      path: "/groups"
      fullPath: "/access/groups"
      preLoaderRoute: typeof AppAccessGroupsRouteImport
      parentRoute: typeof AppAccessRoute
    }
    "/_app/access/tokens": {
      id: "/_app/access/tokens"
      path: "/tokens"
      fullPath: "/access/tokens"
      preLoaderRoute: typeof AppAccessTokensRouteImport
      parentRoute: typeof AppAccessRoute
    }
    "/_app/translations/": {
      id: "/_app/translations/"
      path: "/translations"
      fullPath: "/translations/"
      preLoaderRoute: typeof AppTranslationsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/translations/new": {
      id: "/_app/translations/new"
      path: "/translations/new"
      fullPath: "/translations/new"
      preLoaderRoute: typeof AppTranslationsNewRouteImport
      parentRoute: typeof AppRoute
    }
    "/_app/translations/$locale/$key": {
      id: "/_app/translations/$locale/$key"
      path: "/translations/$locale/$key"
      fullPath: "/translations/$locale/$key"
      preLoaderRoute: typeof AppTranslationsLocaleKeyRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccessRouteChildren {
  AppAccessGroupsRoute: typeof AppAccessGroupsRoute
  AppAccessTokensRoute: typeof AppAccessTokensRoute
  AppAccessIndexRoute: typeof AppAccessIndexRoute
}

const AppAccessRouteChildren: AppAccessRouteChildren = {
  AppAccessGroupsRoute: AppAccessGroupsRoute,
  AppAccessTokensRoute: AppAccessTokensRoute,
  AppAccessIndexRoute: AppAccessIndexRoute,
}

const AppAccessRouteWithChildren = AppAccessRoute._addFileChildren(
  AppAccessRouteChildren,
)

interface AppRouteChildren {
  AppAccessRoute: typeof AppAccessRouteWithChildren
  AppChangelogRoute: typeof AppChangelogRoute
  AppCoverageRoute: typeof AppCoverageRoute
  AppExportsRoute: typeof AppExportsRoute
  AppIssuesRoute: typeof AppIssuesRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppVersionsRoute: typeof AppVersionsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppTranslationsNewRoute: typeof AppTranslationsNewRoute
  AppTranslationsIndexRoute: typeof AppTranslationsIndexRoute
  AppTranslationsLocaleKeyRoute: typeof AppTranslationsLocaleKeyRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccessRoute: AppAccessRouteWithChildren,
  AppChangelogRoute: AppChangelogRoute,
  AppCoverageRoute: AppCoverageRoute,
  AppExportsRoute: AppExportsRoute,
  AppIssuesRoute: AppIssuesRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppVersionsRoute: AppVersionsRoute,
  AppIndexRoute: AppIndexRoute,
  AppTranslationsNewRoute: AppTranslationsNewRoute,
  AppTranslationsIndexRoute: AppTranslationsIndexRoute,
  AppTranslationsLocaleKeyRoute: AppTranslationsLocaleKeyRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
